public class MySampleApexClass {
    public Static Double myValue;
    public Static String myString;
    public MySampleApexClass(){
         myValue=100;
    }
    Public Static Double getCalculatedValue(){
         myValue=myValue+50;
        return myValue;
    }
    public Static Double getCalculatedValuePrice(Decimal price){
        myValue=myValue+Price;
        return myValue;
          
    }
}